// This file is generated by Slice Machine. Update with care!

import ContactForm from './ContactForm';
import Image from './Image';
import Quote from './Quote';
import SearchBox from './SearchBox';
import Text from './Text';

export {
	ContactForm,
	Image,
	Quote,
	SearchBox,
	Text,
};

export const components = {
	contact_form: ContactForm,
	image: Image,
	quote: Quote,
	search_box: SearchBox,
	text: Text,
};
